#ifndef __4802REG_H__
#define __4802REG_H__	

#define EF_BASEADDR			(0x00F800)

	#define Tnvs					*((volatile unsigned char *)(EF_BASEADDR+0x00))
	#define Tpgs					*((volatile unsigned char *)(EF_BASEADDR+0x02))
	#define Tprog					*((volatile unsigned char *)(EF_BASEADDR+0x04))
	#define Tnvh					*((volatile unsigned char *)(EF_BASEADDR+0x06))
	#define Trcv					*((volatile unsigned char *)(EF_BASEADDR+0x08))
	#define Terase					*((volatile unsigned char *)(EF_BASEADDR+0x0A))
	#define Tme						*((volatile unsigned char *)(EF_BASEADDR+0x0C))
	#define Tnvh1					*((volatile unsigned char *)(EF_BASEADDR+0x0E))

	#define EF_plock0		         *((volatile unsigned char *)(EF_BASEADDR+0x10))
	#define EF_plock1		         *((volatile unsigned char *)(EF_BASEADDR+0x12))
	#define EF_plock2		         *((volatile unsigned char *)(EF_BASEADDR+0x14))
	#define EF_plock3		         *((volatile unsigned char *)(EF_BASEADDR+0x16))
	#define EF_plock4		         *((volatile unsigned char *)(EF_BASEADDR+0x18))
	#define EF_plock5		         *((volatile unsigned char *)(EF_BASEADDR+0x1A))
	#define EF_plock6		         *((volatile unsigned char *)(EF_BASEADDR+0x1C))
	#define EF_plock7		         *((volatile unsigned char *)(EF_BASEADDR+0x1E))
         
#define	DMA_BASEADDR		(0x00F900) 

	#define DMA_CTL			         *((volatile unsigned char *)(DMA_BASEADDR+0x00))
	#define DMA_SRC_ADDR_0 			 *((volatile unsigned char *)(DMA_BASEADDR+0x02))
	#define DMA_SRC_ADDR_1			 *((volatile unsigned char *)(DMA_BASEADDR+0x04))
	#define DMA_SRC_ADDR_2			 *((volatile unsigned char *)(DMA_BASEADDR+0x06))
	#define DMA_DST_ADDR_0 			 *((volatile unsigned char *)(DMA_BASEADDR+0x08))
	#define DMA_DST_ADDR_1 			 *((volatile unsigned char *)(DMA_BASEADDR+0x0A))
	#define DMA_DST_ADDR_2 			 *((volatile unsigned char *)(DMA_BASEADDR+0x0C))
	#define DMA_TRANS_CNT_0			 *((volatile unsigned char *)(DMA_BASEADDR+0x0E))
	#define DMA_TRANS_CNT_1			 *((volatile unsigned char *)(DMA_BASEADDR+0x10))

#define	CRC_BASEADDR		(0x00FA00)
	#define CrcResultReg0		     *((volatile unsigned int  *)(CRC_BASEADDR+0x04))
	#define CrcResultReg1		     *((volatile unsigned int  *)(CRC_BASEADDR+0x06))
	#define CrcDataReg  		     *((volatile unsigned int  *)(CRC_BASEADDR+0x80))

#define	DES_BASEADDR		(0x00FB00)
  #define CNTRL_REG		       *((volatile unsigned char *)(DES_BASEADDR+0x00)) 
	 
	#define RAND_REG0		         *((volatile unsigned char *)(DES_BASEADDR+0x20)) 
	#define RAND_REG1		         *((volatile unsigned char *)(DES_BASEADDR+0x22)) 
	#define RAND_REG2		         *((volatile unsigned char *)(DES_BASEADDR+0x24)) 
	#define RAND_REG3		         *((volatile unsigned char *)(DES_BASEADDR+0x26)) 
	#define RAND_REG4		         *((volatile unsigned char *)(DES_BASEADDR+0x28)) 
	#define RAND_REG5		         *((volatile unsigned char *)(DES_BASEADDR+0x2A)) 
	#define RAND_REG6		         *((volatile unsigned char *)(DES_BASEADDR+0x2C)) 
	#define RAND_REG7		         *((volatile unsigned char *)(DES_BASEADDR+0x2E)) 

	#define IV_REG0		       	   *((volatile unsigned char *)(DES_BASEADDR+0x30)) 
	#define IV_REG1		       	   *((volatile unsigned char *)(DES_BASEADDR+0x32)) 
	#define IV_REG2		           *((volatile unsigned char *)(DES_BASEADDR+0x34)) 
	#define IV_REG3		           *((volatile unsigned char *)(DES_BASEADDR+0x36)) 
	#define IV_REG4		           *((volatile unsigned char *)(DES_BASEADDR+0x38)) 
	#define IV_REG5		           *((volatile unsigned char *)(DES_BASEADDR+0x3A)) 
	#define IV_REG6		           *((volatile unsigned char *)(DES_BASEADDR+0x3C)) 
	#define IV_REG7		           *((volatile unsigned char *)(DES_BASEADDR+0x3E))

	#define DATA_REG0		         *((volatile unsigned char *)(DES_BASEADDR+0x40)) 
	#define DATA_REG1		         *((volatile unsigned char *)(DES_BASEADDR+0x42)) 
	#define DATA_REG2		         *((volatile unsigned char *)(DES_BASEADDR+0x44)) 
	#define DATA_REG3		         *((volatile unsigned char *)(DES_BASEADDR+0x46)) 
	#define DATA_REG4		         *((volatile unsigned char *)(DES_BASEADDR+0x48)) 
	#define DATA_REG5		         *((volatile unsigned char *)(DES_BASEADDR+0x4A)) 
	#define DATA_REG6		         *((volatile unsigned char *)(DES_BASEADDR+0x4C)) 
	#define DATA_REG7		         *((volatile unsigned char *)(DES_BASEADDR+0x4E)) 
                                                    
	#define KEY1_REG0		         *((volatile unsigned char *)(DES_BASEADDR+0x50)) 
	#define KEY1_REG1		         *((volatile unsigned char *)(DES_BASEADDR+0x52)) 
	#define KEY1_REG2		         *((volatile unsigned char *)(DES_BASEADDR+0x54)) 
	#define KEY1_REG3		         *((volatile unsigned char *)(DES_BASEADDR+0x56)) 
	#define KEY1_REG4		         *((volatile unsigned char *)(DES_BASEADDR+0x58)) 
	#define KEY1_REG5		         *((volatile unsigned char *)(DES_BASEADDR+0x5A)) 
	#define KEY1_REG6		         *((volatile unsigned char *)(DES_BASEADDR+0x5C)) 
	#define KEY1_REG7		         *((volatile unsigned char *)(DES_BASEADDR+0x5E)) 
                                                    
	#define KEY2_REG0		         *((volatile unsigned char *)(DES_BASEADDR+0x60)) 
	#define KEY2_REG1		         *((volatile unsigned char *)(DES_BASEADDR+0x62)) 
	#define KEY2_REG2		         *((volatile unsigned char *)(DES_BASEADDR+0x64)) 
	#define KEY2_REG3		         *((volatile unsigned char *)(DES_BASEADDR+0x66)) 
	#define KEY2_REG4		         *((volatile unsigned char *)(DES_BASEADDR+0x68)) 
	#define KEY2_REG5		         *((volatile unsigned char *)(DES_BASEADDR+0x6A)) 
	#define KEY2_REG6		         *((volatile unsigned char *)(DES_BASEADDR+0x6C)) 
	#define KEY2_REG7		         *((volatile unsigned char *)(DES_BASEADDR+0x6E)) 
                                                
	#define KEY3_REG0		         *((volatile unsigned char *)(DES_BASEADDR+0x70)) 
	#define KEY3_REG1		         *((volatile unsigned char *)(DES_BASEADDR+0x72)) 
	#define KEY3_REG2		         *((volatile unsigned char *)(DES_BASEADDR+0x74)) 
	#define KEY3_REG3		         *((volatile unsigned char *)(DES_BASEADDR+0x76)) 
	#define KEY3_REG4		         *((volatile unsigned char *)(DES_BASEADDR+0x78)) 
	#define KEY3_REG5		         *((volatile unsigned char *)(DES_BASEADDR+0x7A)) 
	#define KEY3_REG6		         *((volatile unsigned char *)(DES_BASEADDR+0x7C)) 
	#define KEY3_REG7		         *((volatile unsigned char *)(DES_BASEADDR+0x7E)) 

#define	RNG_BASEADDR		(0x00FC00) 
  #define RNGCtrlReg		       *((volatile unsigned char *)(RNG_BASEADDR+0x00))

 	#define RNGModeReg   			 *((volatile unsigned char *)(RNG_BASEADDR+0x08))
 	#define RNGSeqReg0       		 *((volatile unsigned char *)(RNG_BASEADDR+0x10))
	#define RNGSeqReg1       		 *((volatile unsigned char *)(RNG_BASEADDR+0x12))
	#define RNGSeqReg2       		 *((volatile unsigned char *)(RNG_BASEADDR+0x14))
	#define RNGSeqReg3       		 *((volatile unsigned char *)(RNG_BASEADDR+0x16))
	#define RNGData0Reg0 		     *((volatile unsigned char *)(RNG_BASEADDR+0x18))
	#define RNGData0Reg1		     *((volatile unsigned char *)(RNG_BASEADDR+0x1A))
	#define RNGData0Reg2 		     *((volatile unsigned char *)(RNG_BASEADDR+0x1C))
	#define RNGData0Reg3		     *((volatile unsigned char *)(RNG_BASEADDR+0x1E))
	#define RNGData1Reg0 		     *((volatile unsigned char *)(RNG_BASEADDR+0x20))
	#define RNGData1Reg1		     *((volatile unsigned char *)(RNG_BASEADDR+0x22))
	#define RNGData1Reg2 		     *((volatile unsigned char *)(RNG_BASEADDR+0x24))
	#define RNGData1Reg3		     *((volatile unsigned char *)(RNG_BASEADDR+0x26))

#define	RTC_BASEADDR		(0x00FD00)
	#define SIXTEENOFS		         *((volatile unsigned char *)(RTC_BASEADDR+0x00)) 
	#define SECOND   		         *((volatile unsigned char *)(RTC_BASEADDR+0x02)) 
	#define MINUTE		             *((volatile unsigned char *)(RTC_BASEADDR+0x04)) 
	#define HOUR		   	         *((volatile unsigned char *)(RTC_BASEADDR+0x06)) 
	#define DAY		    	         *((volatile unsigned char *)(RTC_BASEADDR+0x08)) 
	#define MONTH		             *((volatile unsigned char *)(RTC_BASEADDR+0x0a)) 
	#define YEAR_L		             *((volatile unsigned char *)(RTC_BASEADDR+0x0c)) 
	#define YEAR_H		             *((volatile unsigned char *)(RTC_BASEADDR+0x0e)) 
	#define SIXTEENOFS_DIS	         *((volatile unsigned char *)(RTC_BASEADDR+0x10))
	#define SECOND_DIS		         *((volatile unsigned char *)(RTC_BASEADDR+0x12)) 
	#define MINUTE_DIS		         *((volatile unsigned char *)(RTC_BASEADDR+0x14)) 
	#define HOUR_DIS		         *((volatile unsigned char *)(RTC_BASEADDR+0x16)) 
	#define DAY_DIS		             *((volatile unsigned char *)(RTC_BASEADDR+0x18))
	#define MONTH_DIS		         *((volatile unsigned char *)(RTC_BASEADDR+0x1a))
	#define YEAR_L_DIS		         *((volatile unsigned char *)(RTC_BASEADDR+0x1c))
	#define YEAR_H_DIS		         *((volatile unsigned char *)(RTC_BASEADDR+0x1e))
	#define ADJUST_INC		         *((volatile unsigned char *)(RTC_BASEADDR+0x20)) 
	#define ADJUST_DEC		         *((volatile unsigned char *)(RTC_BASEADDR+0x22)) 
	#define FORMAT		             *((volatile unsigned char *)(RTC_BASEADDR+0x24)) 
	#define INTERVAL		         *((volatile unsigned char *)(RTC_BASEADDR+0x26))
	#define DIV32768_0		         *((volatile unsigned char *)(RTC_BASEADDR+0x28))
	#define DIV32768_1		         *((volatile unsigned char *)(RTC_BASEADDR+0x2a))
	#define CONF0   		         *((volatile unsigned char *)(RTC_BASEADDR+0x2c))
	#define CONF1   		         *((volatile unsigned char *)(RTC_BASEADDR+0x2e))
	#define PHASE   		         *((volatile unsigned char *)(RTC_BASEADDR+0x30))
	#define RTC_HOLD		             *((volatile unsigned char *)(RTC_BASEADDR+0x32))
	#define RTC_RST		             *((volatile unsigned char *)(RTC_BASEADDR+0x34))

#define LCD_BASEADDR        (0x00FE00)
  #define LCDRAM0            *((volatile unsigned char *)(LCD_BASEADDR+0x00))
  #define LCDRAM1            *((volatile unsigned char *)(LCD_BASEADDR+0x02))
  #define LCDRAM2            *((volatile unsigned char *)(LCD_BASEADDR+0x04))
  #define LCDRAM3            *((volatile unsigned char *)(LCD_BASEADDR+0x06))
  #define LCDRAM4            *((volatile unsigned char *)(LCD_BASEADDR+0x08))
  #define LCDRAM5            *((volatile unsigned char *)(LCD_BASEADDR+0x0A))
  #define LCDRAM6            *((volatile unsigned char *)(LCD_BASEADDR+0x0C))
  #define LCDRAM7            *((volatile unsigned char *)(LCD_BASEADDR+0x0E))
  #define LCDRAM8            *((volatile unsigned char *)(LCD_BASEADDR+0x10))
  #define LCDRAM9            *((volatile unsigned char *)(LCD_BASEADDR+0x12))
  #define LCDRAM10           *((volatile unsigned char *)(LCD_BASEADDR+0x14))
  #define LCDRAM11           *((volatile unsigned char *)(LCD_BASEADDR+0x16))
  #define LCDRAM12           *((volatile unsigned char *)(LCD_BASEADDR+0x18))
  #define LCDRAM13           *((volatile unsigned char *)(LCD_BASEADDR+0x1A))
  #define LCDRAM14           *((volatile unsigned char *)(LCD_BASEADDR+0x1C))
  #define LCDRAM15           *((volatile unsigned char *)(LCD_BASEADDR+0x1E))
  #define LCDRAM16           *((volatile unsigned char *)(LCD_BASEADDR+0x20))
  #define LCDRAM17           *((volatile unsigned char *)(LCD_BASEADDR+0x22))
  #define LCDRAM18           *((volatile unsigned char *)(LCD_BASEADDR+0x24))
  #define LCDRAM19           *((volatile unsigned char *)(LCD_BASEADDR+0x26))
  #define LCDCR0             *((volatile unsigned char *)(LCD_BASEADDR+0x40))
  #define LCDCR1             *((volatile unsigned char *)(LCD_BASEADDR+0x42))
         
#define	Port_BASEADDR		(0x00FF00) 
  #define P0_INT_SEL		 *((volatile unsigned char *)(Port_BASEADDR+0x04))
  #define P0_EDGE_SEL		 *((volatile unsigned char *)(Port_BASEADDR+0x06))
  #define P0_IE    			 *((volatile unsigned char *)(Port_BASEADDR+0x08))
  #define P0_IFG  			 *((volatile unsigned char *)(Port_BASEADDR+0x0A))
  #define P0_PE   			 *((volatile unsigned char *)(Port_BASEADDR+0x0C))
  #define P0_DS       	     *((volatile unsigned char *)(Port_BASEADDR+0x0E))
  #define P0_SEL0         	 *((volatile unsigned char *)(Port_BASEADDR+0x10))
  #define P0_OD     	     *((volatile unsigned char *)(Port_BASEADDR+0x16))

  #define P1_INT_SEL		 *((volatile unsigned char *)(Port_BASEADDR+0x24))
  #define P1_EDGE_SEL		 *((volatile unsigned char *)(Port_BASEADDR+0x26))
  #define P1_IE    			 *((volatile unsigned char *)(Port_BASEADDR+0x28))
  #define P1_IFG  			 *((volatile unsigned char *)(Port_BASEADDR+0x2A))
  #define P1_PE   			 *((volatile unsigned char *)(Port_BASEADDR+0x2C))
  #define P1_DS       		 *((volatile unsigned char *)(Port_BASEADDR+0x2E))
  #define P1_SEL0            *((volatile unsigned char *)(Port_BASEADDR+0x30))
  #define P1_SEL1 			 *((volatile unsigned char *)(Port_BASEADDR+0x32))
  #define P1_SEL2 			 *((volatile unsigned char *)(Port_BASEADDR+0x34))	 
  #define P1_OD      		 *((volatile unsigned char *)(Port_BASEADDR+0x36))

  #define P2_INT_SEL		 *((volatile unsigned char *)(Port_BASEADDR+0x44))
  #define P2_EDGE_SEL		 *((volatile unsigned char *)(Port_BASEADDR+0x46))
  #define P2_IE    			 *((volatile unsigned char *)(Port_BASEADDR+0x48))
  #define P2_IFG  			 *((volatile unsigned char *)(Port_BASEADDR+0x4A))
  #define P2_PE   			 *((volatile unsigned char *)(Port_BASEADDR+0x4C))
  #define P2_DS       		 *((volatile unsigned char *)(Port_BASEADDR+0x4E))
  #define P2_SEL0            *((volatile unsigned char *)(Port_BASEADDR+0x50))
  #define P2_SEL1 		     *((volatile unsigned char *)(Port_BASEADDR+0x52))
  #define P2_SEL2 		     *((volatile unsigned char *)(Port_BASEADDR+0x54))
  #define P2_OD      		 *((volatile unsigned char *)(Port_BASEADDR+0x56))

  #define P3_INT_SEL		 *((volatile unsigned char *)(Port_BASEADDR+0x64))
  #define P3_EDGE_SEL		 *((volatile unsigned char *)(Port_BASEADDR+0x66))
  #define P3_IE    			 *((volatile unsigned char *)(Port_BASEADDR+0x68))
  #define P3_IFG  			 *((volatile unsigned char *)(Port_BASEADDR+0x6A))
  #define P3_PE   			 *((volatile unsigned char *)(Port_BASEADDR+0x6C))
  #define P3_DS       	     *((volatile unsigned char *)(Port_BASEADDR+0x6E))
  #define P3_SEL0            *((volatile unsigned char *)(Port_BASEADDR+0x70))
  #define P3_OD       		 *((volatile unsigned char *)(Port_BASEADDR+0x76))

  #define P4_INT_SEL			*((volatile unsigned char *)(Port_BASEADDR+0x84))
  #define P4_EDGE_SEL			*((volatile unsigned char *)(Port_BASEADDR+0x86))
  #define P4_IE					*((volatile unsigned char *)(Port_BASEADDR+0x88))
  #define P4_IFG				*((volatile unsigned char *)(Port_BASEADDR+0x8A))
  #define P4_PE					*((volatile unsigned char *)(Port_BASEADDR+0x8C))
  #define P4_DS					*((volatile unsigned char *)(Port_BASEADDR+0x8E))
  #define P4_SEL0				*((volatile unsigned char *)(Port_BASEADDR+0x90))
  #define P4_SEL1				*((volatile unsigned char *)(Port_BASEADDR+0x92))
  #define P4_OD					*((volatile unsigned char *)(Port_BASEADDR+0x96))

  #define P5_INT_SEL			*((volatile unsigned char *)(Port_BASEADDR+0xA4))
  #define P5_EDGE_SEL			*((volatile unsigned char *)(Port_BASEADDR+0xA6))
  #define P5_IE					*((volatile unsigned char *)(Port_BASEADDR+0xA8))
  #define P5_IFG				*((volatile unsigned char *)(Port_BASEADDR+0xAA))
  #define P5_PE					*((volatile unsigned char *)(Port_BASEADDR+0xAC))
  #define P5_DS					*((volatile unsigned char *)(Port_BASEADDR+0xAE))
  #define P5_SEL0				*((volatile unsigned char *)(Port_BASEADDR+0xB0))
  #define P5_SEL1				*((volatile unsigned char *)(Port_BASEADDR+0xB2))
  #define P5_OD					*((volatile unsigned char *)(Port_BASEADDR+0xB6))

#define	Port2_BASEADDR			(0x010000)
	#define P6_INT_SEL			*((volatile unsigned char *)(Port2_BASEADDR+0x04))
	#define P6_EDGE_SEL			*((volatile unsigned char *)(Port2_BASEADDR+0x06))
	#define P6_IE				*((volatile unsigned char *)(Port2_BASEADDR+0x08))
	#define P6_IFG				*((volatile unsigned char *)(Port2_BASEADDR+0x0A))
	#define P6_PE				*((volatile unsigned char *)(Port2_BASEADDR+0x0C))
	#define P6_DS				*((volatile unsigned char *)(Port2_BASEADDR+0x0E))
	#define P6_SEL0				*((volatile unsigned char *)(Port2_BASEADDR+0x10))
	#define P6_SEL1				*((volatile unsigned char *)(Port2_BASEADDR+0x12))
	#define P6_OD				*((volatile unsigned char *)(Port2_BASEADDR+0x16))

	#define P7_INT_SEL			*((volatile unsigned char *)(Port2_BASEADDR+0x24))
	#define P7_EDGE_SEL			*((volatile unsigned char *)(Port2_BASEADDR+0x26))
	#define P7_IE				*((volatile unsigned char *)(Port2_BASEADDR+0x28))
	#define P7_IFG				*((volatile unsigned char *)(Port2_BASEADDR+0x2A))
	#define P7_PE				*((volatile unsigned char *)(Port2_BASEADDR+0x2C))
	#define P7_DS				*((volatile unsigned char *)(Port2_BASEADDR+0x2E))
	#define P7_SEL0				*((volatile unsigned char *)(Port2_BASEADDR+0x30))
	#define P7_SEL1				*((volatile unsigned char *)(Port2_BASEADDR+0x32))
	#define P7_OD				*((volatile unsigned char *)(Port2_BASEADDR+0x36))

	#define P8_INT_SEL			*((volatile unsigned char *)(Port2_BASEADDR+0x44))
	#define P8_EDGE_SEL			*((volatile unsigned char *)(Port2_BASEADDR+0x46))
	#define P8_IE				*((volatile unsigned char *)(Port2_BASEADDR+0x48))
	#define P8_IFG				*((volatile unsigned char *)(Port2_BASEADDR+0x4A))
	#define P8_PH				*((volatile unsigned char *)(Port2_BASEADDR+0x4C))
	#define P8_DS				*((volatile unsigned char *)(Port2_BASEADDR+0x4E))
	#define P8_SEL0				*((volatile unsigned char *)(Port2_BASEADDR+0x50))
	#define P8_OD				*((volatile unsigned char *)(Port2_BASEADDR+0x56))
  
	#define ADC_RESULT_L		*((volatile unsigned char *)(Port2_BASEADDR+0xE0))
	#define ADC_RESULT_H		*((volatile unsigned char *)(Port2_BASEADDR+0xE2))
	#define ADC_RESULT			*((volatile unsigned int  *)(Port2_BASEADDR+0xE4))

#define SPI_SCI7816_BASEADDR	(0x010100)	
	#define SPI_CTRL			*((volatile unsigned char *)(SPI_SCI7816_BASEADDR+0x00))
	#define SPI_CONFIG			*((volatile unsigned char *)(SPI_SCI7816_BASEADDR+0x08))
	#define SPI_LEN				*((volatile unsigned char *)(SPI_SCI7816_BASEADDR+0x10))
	#define SPI_BUAD			*((volatile unsigned char *)(SPI_SCI7816_BASEADDR+0x18))
	#define SPI_STATUS1			*((volatile unsigned char *)(SPI_SCI7816_BASEADDR+0x20))
	#define SPI_STATUS2			*((volatile unsigned char *)(SPI_SCI7816_BASEADDR+0x28))
	#define SPI_SDR				*((volatile unsigned char *)(SPI_SCI7816_BASEADDR+0x30))
	#define SPI_RDR				*((volatile unsigned char *)(SPI_SCI7816_BASEADDR+0x38))
	#define SPI_QUERY_CMD		*((volatile unsigned char *)(SPI_SCI7816_BASEADDR+0x40))
	
	#define SCI_CON				*((volatile unsigned char *)(SPI_SCI7816_BASEADDR+0x80))
	#define SCI_MODE			*((volatile unsigned char *)(SPI_SCI7816_BASEADDR+0x82))
	#define SCI_STATUS			*((volatile unsigned char *)(SPI_SCI7816_BASEADDR+0x84))
	#define SCI_DATA			*((volatile unsigned char *)(SPI_SCI7816_BASEADDR+0x8A))
	#define EDC_DATA_H			*((volatile unsigned char *)(SPI_SCI7816_BASEADDR+0x8C))
	#define EDC_DATA_L			*((volatile unsigned char *)(SPI_SCI7816_BASEADDR+0x8E))
	#define SBDRH				*((volatile unsigned char *)(SPI_SCI7816_BASEADDR+0x90))
	#define SBDRL				*((volatile unsigned char *)(SPI_SCI7816_BASEADDR+0x92))
	#define ETU_CNTH			*((volatile unsigned char *)(SPI_SCI7816_BASEADDR+0x94))
	#define ETU_CNTL			*((volatile unsigned char *)(SPI_SCI7816_BASEADDR+0x96))
	#define SCI_CLK_RST			*((volatile unsigned char *)(SPI_SCI7816_BASEADDR+0x98))
	#define SCI_INT_EN			*((volatile unsigned char *)(SPI_SCI7816_BASEADDR+0x9A))	

#define CAL_BASEADDR (0x010200)
    #define CAL0				*((volatile unsigned int *)(CAL_BASEADDR+0x30))
    #define CAL1				*((volatile unsigned int *)(CAL_BASEADDR+0x32))
	#define CAL2				*((volatile unsigned int *)(CAL_BASEADDR+0x34))
	#define CAL3				*((volatile unsigned int *)(CAL_BASEADDR+0x36))
	#define CAL4				*((volatile unsigned int *)(CAL_BASEADDR+0x38))
	#define CAL5				*((volatile unsigned int *)(CAL_BASEADDR+0x3a))
	#define CAL6				*((volatile unsigned int *)(CAL_BASEADDR+0x3c))
	#define CAL7				*((volatile unsigned int *)(CAL_BASEADDR+0x3e))

#define	EFlASH_PAGELOCK_BASEADDR	(0xFF0000)
	#define USERPAGELOCK0		*((volatile unsigned char *)(EFlASH_PAGELOCK_BASEADDR+0x86))
	#define USERPAGELOCK1		*((volatile unsigned char *)(EFlASH_PAGELOCK_BASEADDR+0x87))
	#define USERPAGELOCK2		*((volatile unsigned char *)(EFlASH_PAGELOCK_BASEADDR+0x88))
	#define USERPAGELOCK3		*((volatile unsigned char *)(EFlASH_PAGELOCK_BASEADDR+0x89))
	#define USERPAGELOCK4		*((volatile unsigned char *)(EFlASH_PAGELOCK_BASEADDR+0x8A))
	#define USERPAGELOCK5		*((volatile unsigned char *)(EFlASH_PAGELOCK_BASEADDR+0x8B))
	#define USERPAGELOCK6		*((volatile unsigned char *)(EFlASH_PAGELOCK_BASEADDR+0x8C))
	#define USERPAGELOCK7		*((volatile unsigned char *)(EFlASH_PAGELOCK_BASEADDR+0x8D))

	#define USERPASSWORD0		*((volatile unsigned int *)(EFlASH_PAGELOCK_BASEADDR+0x90))
	#define USERPASSWORD1		*((volatile unsigned int *)(EFlASH_PAGELOCK_BASEADDR+0x92))
	#define USERPASSWORD2		*((volatile unsigned int *)(EFlASH_PAGELOCK_BASEADDR+0x94))
	#define USERPASSWORD3		*((volatile unsigned int *)(EFlASH_PAGELOCK_BASEADDR+0x96))
	#define USERPASSWORD4		*((volatile unsigned int *)(EFlASH_PAGELOCK_BASEADDR+0x98))
	#define USERPASSWORD5		*((volatile unsigned int *)(EFlASH_PAGELOCK_BASEADDR+0x9A))
	#define USERPASSWORD6		*((volatile unsigned int *)(EFlASH_PAGELOCK_BASEADDR+0x9C))
	#define USERPASSWORD7		*((volatile unsigned int *)(EFlASH_PAGELOCK_BASEADDR+0x9E))


#endif				